name: UI autotest

on:
  push:
    branches:
      - main  # Запускать на коммитах в main ветку
  pull_request:
    branches:
      - main  # Запускать workflows, когда будет сделан pull request в ветку main

jobs:
  run-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install project requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run UI test with pytest and generate allure results
        run: |
          pytest -m regression --alluredir allure-results 

      - name: Upload allure-results package
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: allure-results
          path: allure-results

  publish-report:
    if: always ()
    runs-on: ubuntu-latest
    needs: [run-test]

    steps:
      - name: Get allure history
        uses: actions/checkout@v6
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Download allure results
        uses: actions/download-artifact@v7
        with:
          name: allure-results
          path: allure-results

      - name: Generates allure report with history
        uses: simple-elf/allure-report-action@v1.13
        if: always()
        with:
          allure-results: allure-results
          allure-history: allure-history

      - name: Deploy report to GitHob Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
